services:

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
      - api1
      - api2
      - api3

  frontend:
    build: ./frontend
    restart: unless-stopped

    develop:
      watch:
        - action: rebuild
          path: ./frontend

  api1:
    build: ./api
    restart: unless-stopped
    ports:
      - "5001:5000"

    develop:
      watch:
        - action: rebuild
          path: ./api

  api2:
    build: ./api
    restart: unless-stopped
    ports:
      - "5002:5000"

    develop:
      watch:
        - action: rebuild
          path: ./api

  api3:
    build: ./api
    restart: unless-stopped
    ports:
      - "5003:5000"

    develop:
      watch:
        - action: rebuild
          path: ./api

  mysql:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mongo_salon

networks:
  default:
    name: mongo-salon-network