events {
    worker_connections 1024;
}

http {

    upstream salon_api {
        least_conn;

        server api1:5000 max_fails=3 fail_timeout=30s;
        server api2:5000 max_fails=3 fail_timeout=30s;
        server api3:5000 max_fails=3 fail_timeout=30s;
    }

    server {

        listen 80;

        location /api/ {

            proxy_pass http://salon_api;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_connect_timeout 30s;
            proxy_send_timeout 30s;
            proxy_read_timeout 30s;
        }

        location / {

            proxy_pass http://frontend:80;

            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}